### PR TITLE
Adds constructable and upgradeable machinery, fixes the RPED, other minor fixes

### PR DESCRIPTION
**Pull request by mvanalphen**
Changes:
1) Adds various constructible and upgradeable machinery. See [this pastebin](http://pastebin.com/qQt6xgkD) for details on the upgrades.
2) Fixes the Rapid Part Exchange Device (RPED).
3) Fixes Unathi/Skrell hardsuit conversions.
4) Adds a proper NanoUI interface for the cloning computer.
5) Gives drones soap, so they can clean without having to go to a recharger every three sprays. Drones can now also clean up broken bottles.
6) Gives security and clerical borgs recorders.
7) Updates the teleporter as part of the machine upgrades, it is now identical to /tg/'s. Can be set to teleport to "Teleporter" (which are the current tracking beacons and bluespace gigabeacons) and "Gate", which can be set by first finding another teleporter, unscrewing the panel, using a multitool on it to download its buffer, and then using the multitool on your own teleporter to upload its data. It can also teleport you directly to players with tracking implants (so they actually serve a proper purpose). Additionally, if you teleport somewhere using telescience with a GPS inserted into the telescience console, you can save its last teleported position, put it in the teleporter console and teleport there.
8) Fixes mops not working with space cleaner.
9) Fixes holographic sign projectors not allowing you to project new signs after projecting 10.
10) Windows now update colors when built.
11) Several security rooms were made separate areas with independent APC's per the rest of the map.
12) Lets the AI state laws over specified channels. Also allows borgs to state laws automatically.
13) Other minor (map) fixes.

### CODE REVIEW

**Comment by PJB3005** [comment]
Awesome! Fox, you better merge this

**Comment by Fox-McCloud** [comment]
Awesome; really wish our coding issues were resolved; I'd love to have this in yesterday.

If you're up for it, go ahead and port over TG's tesleci console, GPS, and telepad code as this fits in nicely with it.

For the  GPS specifically, you'll notice there's two types: there's the "GPS" which is called "SPS" and there's the other GPS that relates to Xenoarch. Feel free to rename the Xenoarch GPS to something else and ensure the current SPS is named GPS (will just make more sense in the long run).

Very excited for this one; thank you so much for porting this over.

**Comment by mvanalphen** [comment]
Sure, I can port that over tomorrow. I happen to have touched telesci's code today as part of the teleporter upgrades, so I'll port over the rest of the code as well.

**Comment by mvanalphen** [comment]
Just a note: the syndicate station starts with an upgraded teleporter so their teleports never fail.

**Comment by fj45** [comment]
Quick note, is it also possible to add the mining/engie/whatever other GPS units? If we don't already have those. Even if they were only added as something science could build for now.

**Comment by mvanalphen** [comment]
They're in the code, just not on the map. I'll see about adding them when I port telescience.

**Pull request merged**
