### PR TITLE
Complete Disposals Overhaul

### PR DESCRIPTION
**Pull request by Tsundancer**
-Entire disposals pipe loop rebuilt from the ground up to be less shitty.
-Removed request consoles in customs checkpoints to make room for disposal chutes.
-Moved crew monitoring computer in Blueshield office and moved the liquor cabinet down to make room for chute (RIP in peace desk lamp)

### CODE REVIEW

**Comment by Tsundancer** [comment]
http://imgur.com/xXMx3Hv

Screenshot of map.

**Comment by Tsundancer** [comment]
Great. So all my hard work is thrown immediately down the shitter because this was repeatedly passed over to commit other things.

**Comment by ghost** [comment]
You added the commit with no warning or discussion with anyone, so far as I know.

I know for a fact you didn't talk with any of the code maintainers about this change. 

Paradise Staff are not obliged to pull your work in simply because you made it, especially if you don't talk about these changes at all prior to submitting them. If you want to be certain your PRs will be merged, talk to people prior to submitting them.

My apologies your work was lost, but communication is key.

-Dave

**Comment by Tsundancer** [comment]
I was talking about it in depth for days in the IRC both before and while I was working on it. 

The main point though is that PRs submitted after this one were committed without so much as a second thought. It seems really dumb to commit things out of order, because it causes things exactly like this. Even just glancing at it, and seeing over 1800 lines changed, you would think the person doing the pulling would at least ask about it once, or respond even once to my multiple direct queries about it.

Hell, even glancing at the title without even opening it. "Complete Disposals Overhaul" it seems like that's the kind of wording that gets across it's a massive change that needs to be committed sooner rather than later.

**Comment by Fox-McCloud** [comment]
I was not notified of this change ahead of time (the only notification I ever got about it was you spam-sending me the link to this three times in a row, without a word), and it was not discussed with anyone on the administrative team--just talking about it on the IRC with a group of people there means nothing; the IRC is largely a chat room; unless you've talked with admins privately, don't consider anything there, binding; most there are players.

As Dave said; submitting a PR doesn't mean it's going to get merged; no one is entitled to this, and any PR can be rejected for any reason. 

As for this PR in particular? I'll be honest, I don't have an interest in merging it; the disposals system works fine and is completely functional. Yes, there's some loops that are oddly long, but there's really no reason for it to be completely overhauled at this point in time, especially since it fully works.

**Pull request closed without merging**
