### PR TITLE
Adds Rapid Part Exchange Device

### PR DESCRIPTION
**Pull request by GhostAA12**
This item allows items in machinery to be changed without disassembling them.

### CODE REVIEW

**Comment by ZomgPonies** [comment]
Need more details as to what this actually does first, before I decide if it's needed in the codebase.

**Comment by Iamgoofball** [comment]
We have this over at tg, it's a godsend for upgrading machines.

Basically, what you do is you stick upgraded versions of stock parts into the RPED. You can then unscrew a machine, click on the machine with the RPED, and it will swap out all the old stock parts with whatever versions you put into it.

Say I want to upgrade my Protolathe. I'll print out two super matter bins, and 2 pico manipulators. I'll stick these items into the RPED. Then, I'll unscrew, but not completely dismantle the Protolathe. Then I click on the machine. The RPED will swap out the old parts for the new ones, allowing you to upgrade the machine without needing to resync it, or it deleting the minerals inside of it, which happens when you completely dismantle the machine.

It's a fucking awesome tool over at TG, and it makes upgrading shit easy as fuck.

**Comment by GhostAA12** [comment]
Basically what Iamgoofball said. It's really handy in science.

**Comment by ZomgPonies** [comment]
Update PR so it can be merged in.

**Comment by GhostAA12** [comment]
It's been updated

**Pull request merged**
