### PR TITLE
Map changes

### PR DESCRIPTION
**Pull request by W3bster**
-Complete rework of viro wing.
-Modified toxins mixing walls for a higher temp resistance.
-Changed pipes in atmos to fit the distro and waste system upon request
of Bone White.
-Moved flora labs to fit more xenobio and feel less rejected.

### CODE REVIEW

**Comment by IndexLP** [comment]
Love the work as always, my only concern is the lack of an Interior/exterior door group, where only one can be open at a time, to at least the lab portion of the new virology area. I can see why the patient wing would want to drop it for ease of getting quarantined people back there, but the lab should still have the interior/exterior door group. The lack of a shower in the decontamination area between said doors is also strange to me.

This is not a working mock-up, but is an idea of the way I think the Viro area can be improved to make the lab look/feel more secure, with those concerns in mind.
virosuggestion

**Comment by W3bster** [comment]
Hm. Your version of it looks much more better. Mind if you could commit this?

**Comment by IndexLP** [comment]
Sorry I can't. As I mentioned, the map is not actually useable, I didn't even use the map tool in the tools folder first as I never intended it to upload. among the issues I don't know how to tie doors together or to buttons for instance, but feel free to try to modify the map to make it work., or just use the image as a reference. Here is the .dmm file if you want it though: https://dl.dropboxusercontent.com/u/61681687/cyberiad.dmm

**Comment by W3bster** [comment]
Updated to add the disinfection thing and better viro-to-patient access. Didn't add the airlock systems since it would be horridly long and clusterfucky to do.

**Pull request closed without merging**
