### PR TITLE
Balance fix tweak round1

### PR DESCRIPTION
**Pull request by Fox-McCloud**
This is basically the previous patch minus map changes and "controversial" things.

What's changed:

-All medical reagents now health analyzer scannable; all non medical are not.
-Added in mute toxin (for future parapen nerf) and recipe
-adds in paracetamol recipe
-Sleeper can inject paracetamol; the overall reagents you can inject is slightly lessened (Bay)
-Smoking Pipes now hold reagents and last much longer (no more relighting every 2 minutes)
-High amounts of electricity in the grid will cause you to be arc flashed if you touch something that's electrified (very deadly)
-Hyperzine works again
-Medical Pain Shock system harmonized with Bay's shock system
-Removed Dionea immortality; that said, you'll be able to clone them, once again.
-Vox now have blood (logical, and more Bay harmonizing)
-Sleep Toxin buffed back to its original status (again, will coincide with future parapen nerfs)
-A few foods have logical reagents in them (fried rice has...rice, etc).
-Removed multiple duplicate instances of "blank" virus symptoms; will still be possible to get, but they'll have name now and be much harder to find.

-NO map changes (may come in the future)

### CODE REVIEW

**Comment by ZomgPonies** [comment]
-Removed Dionea immortality; that said, you'll be able to clone them, once again.

Reasoning?

**Comment by Fox-McCloud** [comment]
Sure. It's completely overpowered. You kill them, and they just instantly respawn as a nymph (with ventcrawl and who can use tools, none the less). If nymphs were as slow as their adult counterparts and lacked Ventcrawl, it would probably be fine, but they do have these two abilities. 

The race itself has massive regen, pain immunity, rad absorb, and no breathing for being slow; I figured they didn't really need to be immortal, as well, on top of all their abilities.  

Spoke with Neca about this and he was in agreement that it needed to go.

**Comment by FalseIncarnate** [comment]
They should have some other weaknesses like Plant-B-Gone and more susceptible to fire, plus I believe their regen only works in decent lighting.

Code wise, not sure where those are at in terms of actually working right, but an infinite respawn without assistance does seem a bit unfair.

Perhaps they should revert to a seed state that has to be planted, grown, and then they pop out fully grown?

I know the replicant cloning doesn't work right now, but I'll be working at it as I continue with the Hydro fixes

**Comment by Bone-White** [comment]
"-Removed multiple duplicate instances of "blank" virus symptoms; will still be possible to get, but they'll have name now and be much harder to find."

This was there to easily simulate the commonplace nature of blank symptoms, as with the original (and now revised) method, all symptoms had the same chance of occuring.  With the method I used, I wanted to have "blank" symptoms more common, to make virology less instantly griefy.

**Pull request merged**
