### PR TITLE
AI fixes, borg fixes, minor map fixes

### PR DESCRIPTION
**Pull request by mvanalphen**
Changes:
1) Fixed a typo in the Crew Monitoring AI button.
2) The AI is now able to use regular channels using its built-in radio, rather than having to use the intercoms. So if you want to speak in the command channel, simply use :c. 
3) Borgs can now send PDA messages.
4) Borgs can now use the camera console.
5) Borgs can now be dragged when their battery is damaged, out of charge or missing.
6) When the AI's wireless (or transceiver) is disabled, it can no longer talk/interact with doors.
7) Minor map fixes.
8) Fixes blindfolds.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
Does this also fix the subspace transceiver on AI Cards? Currently if you disable it, the AI can still talk its head off (on a related issue, disabling wireless apparently also doesn't stop them from using short-cuts to open/close things and borgs/AI can bypass firewalls by ALSO using shortcuts).

On a related note, I've had reports that when borgs run out of power now, they're literally incapable of being moved; not even outside intervention can help them.

**Comment by mvanalphen** [comment]
You're right, they indeed couldn't be moved. It was caused by some movement code I initially ported from Bay to fix the issue, but which was eventually not necessary anymore as I chose a different solution (paralyzing the borg, which is also what happened when you ran out of charge). The most recent commit should fix that: they still won't be able to move, but they can be pulled around.

As for the AI cards, I don't know if it fixes that. I can look into fixing that tomorrow.

**Comment by fj45** [comment]
That podbay change won't conflict with what I did, correct?

And what podbay did you change exactly?

**Comment by TheDZD** [comment]
One thing you may want to have a look at is cyborgs using camera monitors, as I have tried checking the singularity monitor as a cyborg and been rejected due to insufficient access.

**Comment by mvanalphen** [comment]
It won't fj45, the changes were made after I merged your changes. The podbays that were modified were the ones you changed, and the changes that were made aren't noticeable (just added a missing air alarm and extended the area).

Posting a commit to fix the issue with borgs accessing camera consoles in a few minutes. I wasn't aware borgs could previously access camera consoles.

**Comment by mvanalphen** [comment]
Hold off on merging this for now please - I'll investigate the AI issues tomorrow.

**Comment by mvanalphen** [comment]
@Fox-McCloud Ready for merging.

The AI can no longer speak if its wireless transceiver is disabled through the Intelicard, and it can no longer access doors when its wireless connection is disabled.

**Comment by mvanalphen** [comment]
There were some encoding issues that have been resolved now. I recommend no one edits say.dm, as it's a major PITA.

**Comment by Fox-McCloud** [comment]
There's been a recent problem that's cropped um that may put this on hold, unless you know where it originates from.

Basically AI_eye isn't functionining properly and the AI cannot move its "vision"...likewise there's another where player panel and player panel new are not showing up. Both of these are runtime errors.

**Comment by mvanalphen** [comment]
Do these issues occur on the server itself without this code being merged, or when this code is actually applied?

I did run into this issue for a while, where for an inexplicable reason I got runtime errors initially stating that .null/turf couldn't be modified, which in turn caused BYOND 6#### issues. I couldn't really figure it out, so I started manually debugging everything, and I figured the only change that could've caused this is the encoding of say.dm, as no other changes could possibly cause that. I re-encoded it, re-compiled and the issue had disappeared.

If this is an issue which pops up on the server without this code being merged, I will investigate and see what causes it, as up until now I presumed it was caused by my code changes, and seeing as the issue stopped showing up I figured it was fixed.

**Comment by mvanalphen** [comment]
So I've done some testing, and based on that it seems that whenever the Russian encoding is enabled (together with these changes) the eye.dm issues pop up and BYOND starts shitting itself. I've gone ahead and commented out the Russian encoding. It may not be a great solution, but so be it. Plus, if there's any Russians playing on Paradise in the first place, they are able to use regular chat as well, so this is a mere convenience for them.

**Comment by mvanalphen** [comment]
Re-opening as new pull request with one commit due to the clusterfuck this has become

**Pull request closed without merging**
