### PR TITLE
Mapping fixes and changes

### PR DESCRIPTION
**Pull request by IcyV**
Autolathe added to engineering and RnD
Several more RCSs added
Collectors added to Engineering secure storage
rods+metal+glass added to primary tool storage
Second pair of insulated gloves added to tech storage
Crate in maintenance with minor items
Hot Drinks vending machine added to bar
Canes added to medbay
Safe added to Viro
Beakers added to the drug lab
Supermatter engine room removed
Secondary incubation machine removed from Viro
Toxins adjusted to be more straight-forward.
Minor piping/cable issues fixed

### CODE REVIEW

**Comment by Regen1** [comment]
Why is supermatter being removed?

**Comment by Bone-White** [comment]
Indeed, there's nothing wrong with the supermatter engine I thought, it's a viable alternative to the singularity, in fact I prefer it personally.  At least it gives you a warning when it's about to go critical, unlike the singularity.

**Comment by IndexLP** [comment]
I don't know how to feel about this change. I dislike the SM for a couple of reasons. It's not very interactive from a game-play standpoint, a problem it shares with all the other power generation sources. And it's more dangerous than any sensible corporation would allow on the ship given NT hiring policies, a problem it shares with the singularity.

But at least it helps to shake up engineering by having three different options for power generation, even if that choice is contained only to the start of the round. I think I DONT support the removal of the SM without adding in another, preferably more interactive, engine. Although if you wanted to get rid of the singularity be my guest, that thing is just bad.

**Comment by Fox-McCloud** [comment]
It's simple, really.

No one ever uses it; the only time it's ever used is when a traitor wants to cause chaos or a rogue AI wants to make everyone pass out from hallucinations every minute or two. Furthermore, it doesn't allow for experimentation with high power output like the singularity does (an important feature for traitor engineers). 

I'll disagree, also, that the Singulo doesn't warn you before becoming overloaded---the SM gives a text based warning, while the Singulo gives a visual one.

As for interactive engines, you're never going to get what you're looking for; all engines in SS13 since it's inception have had that problem--even if they're touchy like the Supermatter, inevitably, the most optimal+safe+sustainable method of running them is presented to everyone as the way to do it, and that's all anyone ever does; it's been this way with the combustion engine, the original supermatter, the singulo, and here the supermatter 2.0. 

Plus, from a realism/IC standpoint, a station would never spend the money on two ultra-high tech engines, nor would they want to hand out paychecks to multiple highly specialized engineers trained in the specific engines to operate them.

So, I definitely agree with this change; let the supermatter die the death it deserves; it serves nothing more than serve as a giant traitor item and additional reservoir for power with its 3 additional SMESes. An "option" that never gets used is no option at all.

**Comment by M3hillus** [comment]
As for the decision to remove the super-matter engine, I understand the reasoning behind the removal of it.

However, I don't understand the Irrational fears associated with it, and the utter lack of understanding how it works by almost everyone. It has become almost a taboo to even mention using it.

As for a means of power generation, perhaps it should be moved to a more research side, as fluff wise, NT is all about plasma, plasma production, and the support of such. Everything on the station can be tied to that goal, and the support of such. As to why NT would not be interested in the SM for research and extraction is beyond me.

Game-play wise, the SM engine room has been constantly been poorly designed and without experience using it, I agree it can be a huge hazard to operate, and due to fears and misconceptions regarding it delaminating, nobody bothers trying to use it, even in the most basic of ways.

As a means of power generation, it generates a comparable amount to the singularity engine, but most importantly, when it fails, it doesn't create a lag-inducing, shuttle calling, round destroying monstrosity known as "Lord Singuloth". It just blows up, a sizable amount mind you, and creates a blast of radiation. On all Z levels, everywhere.

Instead of just removing it, I propose it be moved to a spot, much like the bomb testing range, and have the radiation blast not affect the entire playable area in the game if it does blow. Perhaps even Implement it into Toxins research, and outright remove a large amount of the plasma stored there, instead moving to extraction from the SM itself if any sizable experimentation be wanted. With a proper nerfing of the radiation blast to something acceptable, I can see it making toxins a bit more entertaining, at least from my perspective.

I think the supermatter is getting a death it does not deserve, and has more of a place on the station than a black hole.

**Comment by ZomgPonies** [comment]
Not merging this in until the question of supermatter gameplay is resolved. This is a MAJOR change and should have been discussed WAY before putting up a PR as a fait accompli.

**Comment by Regen1** [comment]
Sorry Fox, but I stopped reading at "Nobody uses it"
You haven't been playing in what, half a year? I feel that you have little to say in the regards about how much it is used

As for the Supermatter? I've seen it been used multiple times, traitors doesn't usually go to it, and it gives off much more of a warning before it explodes, unlike the Singularity which has no "oh fuck" button, nor does it have any global message saying it is about to eat everything.

**Comment by IcyV** [comment]
In my experience, 9 out of 10 times on the semi-rare occasion that the SM is used ends up with it exploding and just screwing the round even further.

**Comment by M3hillus** [comment]
As compared to the singularity though, a SM explosion is nearly nothing. Yes, its a sizable explosion, and yes, people get a load of radiation, but that's a fixable thing. The only way to stop a singularity release is another singularity IIRC, or a sizable explosion. Coupled with the lag it produces, I'd sooner see the singularity engine removed and the Supermatter becoming the main engine, but that's a personal opinion.

**Comment by IcyV** [comment]
The supermatter calls the shuttle entirely a lot of the time. If medbay isn't running at least somewhat decently, there is no way in hell that most people will go to get the anti-tox they need. This leaves half the crew damaged, puking, and not willing to go on any further or just dealing with issues for however long it takes for them to finally get treatment. This ranges from a few minutes if medbay is really on the spot, or never happening at all.

The singulo is much more deliberate and often punished. It has a much lower rate of actually failing and messing the round up. The singulo is definitely an item that can cause mass destruction and is usually round-ending. I'm not claiming that its better, buts its practically safer and more efficient in every way.

**Comment by W3bster** [comment]
I'd agree with IcyV on this issue. Not enough people even know how to properly and efficiently setup that engine. Most think it's like the Singulo, a "Setup and leave" engine that you have to shoot a few more times with emitters when it gets low. But no. The SM is an engine that requires CONSTANT watch if you wish for it to be effficient. You have to pump out the toxins, constantly manually cool (or setup a cooling system if you are multiple engineers willing to work on it), inject and remove N2. And no, you don't teach that on a whim like you do with the Singularity. Right now, people at roundstart will remove the emitters from the SM and just leave it there. And the second it begins overload they space it. I have yet to see a successful and efficient setup of that engine in the entire time that i have played on Para.

If anything, removing it can help us make more space for more things that may actually be used!

**Comment by Fox-McCloud** [comment]
Further testing will be needed, but the engine doesn't seem capable of sustaining a 600,000 watt output safely for the entire duration of a round.

**Comment by M3hillus** [comment]
Its the nature of the current setup I am afraid, unless atmospherics is involved or the engine pipework, or just plain design, is changed drastically. 

The ability to Build, Deconstruct, and upgrade coolers, and heaters, would help drastically.
Also, due to the length of the rounds, either the output tanks would need to be replaced, or rigged for the output gas getting sent to atmos itself as the 3x3 tanks can contain, as far as I know, a damn near infinite amount of gas.

**Comment by VampyrBytes** [comment]
Sorry, but I can't support this. Reducing options just because something isn't used much IMO just reduces the game experience. There's other things that aren't used much, like Telecomms scripting, should we get rid of them too?

There was talk in skype a while back about replacing the supermatter with a combustion engine which I would support as it doesn't reduce the options, just changes them, but just straight out removing it, no

**Comment by Fox-McCloud** [comment]
I see telecomms scripts roughly every 2-3 rounds; the Supermatter is lucky to be used once every 20.

More options isn't always a good thing; under that premise, then the gas turbine, supermatter, RUST, TEG, antimatter, and singulo should all be crammed into engineering for "more options" and never removed because it's "reducing options". False choices aren't real options at all; they're just clutter or mechanics that tend to only get left around for more...abusive purposes (A prime example of this was Xenoarch before the artifact detector was added; the only thing the research station was ever used for was a chem lab and free stun baton).

Combustion would be fine, but the code is just too old and has a number of limitations placed on it because of that.

**Pull request closed without merging**
