### PR TITLE
New Job - Head - Non-Karma - "Head of Internal Affairs"

### PR DESCRIPTION
**Pull request by IndexLP**
If pulled, before compiling please be sure to check code/WorkInProgress/IndexLP/indexlp_defines.dm
##### Reason for Creation

This job was developed based of of a conversation Neca and I had a few months ago where I lamented that there wasn't more of a presence by Centcom for Internal Affairs Agents to turn to when the captain was busy or MIA, but the Internal Affairs Agent felt he had things he should be doing to do his job. This job is needed to fulfill that role without placing extra burden on the admin staff. 

As a player who frequently (read:near always) plays IAA it's not at all uncommon to have no one to report to, either there is no magistrate on job (the current superior for IAAs) or the Captain is busy/mia/ dontcarenotyourbossanymore (the old superior).

This job was _not_ created as a karma job because of the potential to lead to the same problem as the magistrate, the position hardly gets played. 

I don't feel this job violates the lore either as Internal Affairs is an established Centcom agency.
##### Role on the Station

The role of the Head of Internal Affairs is to give the Internal Affairs Agents an authority to report their findings to reliably. And as this authority the Head of Internal Affairs would have the power to demote/fire or discipline crew members that breached the rules and regulations set down by Central Command (SoP), however this is not an office of security and so would not determine punishments for crimes committed, although the position may inform security when they feel security is conducting themselves illegally (ie 20 min brigging for first offense trespassing)

I don't feel this role overlaps in a significant way with the HoP as the HoIA would not process job transfer additional access or any other HoP function besides demotion, and the HoP would still be in charge willing demotions (job change to civilian; quitting).

Basically the HoIA would act as an authority behind the Internal Affairs Office, which would provide an RP based, rather than admin based, check on mild-moderate shitcurity (as well as other jobs), as well as give more meaning to the Internal Affairs Agents who would now operate directly under a dedicated authority.
##### Supervisor.dm Code SnapShot
- Total Positions: 1
- req-admin-notify: yes (1)
- minimal_player_age: 30 The job has a petty heavy responsibility/authority, but not more than the captain, that could ruin someones round if played inexperienced player, so I went with the same minimum age to be safe
- access = 'Same as NT rep + HoIA office' Conflict resolution and investigations, part of the IAAs (including the HoIA) job, typically requires access, being that this is a head i didn't see the harm in giving the HoIA a large access list.
- Loyalty Implanted
- Magistrate given access to HoIA office
##### Access.dm Code SnapShot
- access_hoia = "72"
- access_hoia added to the appropriate functions in access.dm
##### Jobs.dm Code SnapShot
- Defines the unique FLAG "HOIA" and makes HOIA a command position and puts it in the support category.
##### indexlp_defines.dm Code SnapShot
- Defines a new area for the HoIA office.
- Defines a new encyptionkey for a newly defined radio for the HoIA  Acts similar to captains headset due to potential need to communicate with any department
##### indexlp_icons.dmi Icon SnapShot
- Contains the icon for the encryption key
### Map Changes

As this new job requires an office I made one for it, I located it where the clown office currently is and moved the clown office to another part of the ship (next to the dancehall above the library/chapel with a new hallway; see the attached map images.) This room has a new area definition for it.

The Clown office is unchanged other than the blast door having been removed and being slightly shuffled around to accommodate it's new position. The HoIA office is a functioning room that contains these items of note:
- ID Computer
- Employment Record Laptop
- Head of Internal Affairs Fax Machine (HoIA reports to CentCom)
- Law Office Stamp (MOVED from the law office to HoIA office)
- HoIA Spawnpoint

internalaffairsarea
(Above: Slightly Old image, the see-through door and opaque door are swtiched)
clownoffice
(Above: Slightly Old image, the window in the top  left corner of the clown office was moved up one space and that spot was filled in with a reinforced wall.)
## Central Command Jacket

A default item for the HoIA, it's a jacket, but I put the centcom patterning on it, it works just like the jacket and can be buttoned and un-buttoned (the standard NT centcom uniform was way too TNG first season for me)
##### indexlp_defines.dm Code SnapShot
- Defines the new item: the Central Command Jacket, uses sprite_sheets to maintain compatability with other icon additions by using it's own .dmi
##### indexlp_icons.dmi Icon SnapShot
- Contains both the obj icons (buttoned and un-buttoned) and mob icons (all direction both buttoned and un-buttoned) for the Central Command Jacket.

indexlp_icons_large

indexlp_icons

This is my first foray into the code, so if there is anything I missed that you need to make a job please let me know, that said, everything compiled and seemed to work. Thanks for considering the pull request.

### CODE REVIEW

**Comment by ZomgPonies** [comment]
I'm not sure how important a new job like this is, since it overlaps quite a bit with magistrate. I've seen a fair amount of magistrates spawn in regularly and when they do shitcurity tends to drop quite a bit. I expect magistrates to become a regular spawn once I add gameplay specific to them.

**Comment by IndexLP** [comment]
I have seen very few magistrates, and I don't seen the overlap in any case. Perhaps it's because I have seen so few magistrates, but I got the feeling they were much more like a judge, focused on criminals and a court of law. Not on employee review and ensuring SoP is being followed.

If there was a job HoIA was similar to it would be NT Rep, but where as the point, as I see it, of the HoIA is to actually manage certain aspects of the ships operation, namely it's adherence to SoP, the point of an NT is much more as an advisor to the heads of staff.

To be totally honest, If I had not spawned in as an Internal Affairs Agent and someone told me they reported to the magistrate I'd think they were mistaken. I don't see what makes a judge the boss of an corporate minder (Except when the internal Affairs Agent has the alt title of a lawyer or public defender.) Back when the IAAs reported to the captain they had as good of a chance of being blown off as being listened to, because there was no clear connection as to why they reported to the captain, and I think this problem is much worse with the magistrate as their head.

I see a wide difference between the magistrate and this, job, but I suppose that could be because I have seen so few of them, and even if that is the case, the name of the position still irks me because I don't really see the connection as mentioned above.

Also I would just like to note, that the job wasn't created for one purpose, but a large part was giving IAA a relevant boss, any drop in shitcurity would be nice, but ultimately not even a side-purpose to why I feel it should be added.

[Merge conflict resolved by adding a a magistrate spawn location is roughly the same spot.]

**Comment by VampyrBytes** [comment]
It seems like an easier way would be to just separate IAA job from the lawyer/PD jobs, and make IAA's boss the NT rep.

You're making a 'head' position that only covers one position, that isn't always filled anyway.

Making IAA a separate job now that there's magistrates does make sense though, as the existence of magistrates could well lead to more people playing lawyer/PD, and IAA's responsibilities would normally be considered over and above those of a lawyer's. Who they should answer to is a matter of opinion

**Comment by IndexLP** [comment]
My main concern is that IAA not be a position where your effectiveness is reliant on the person doing the wrong, deciding to listen to you or not. I'm saying from experience, that having someone who is only kinda sorta related to the IAA leading them just leads to them ignoring the IAA, even when the IAAs have a valid point, and sometime the person leading them is just to busy with other more relevant to them duties. I feel like NT Rep could be close enough to overcome this, but what does it mean for an NT rep to lead the IAs department? The paper sitting on the NT Reps desk makes clear he is only an adviser, I don't much care if it stays that way, but for him leading the IAA to have any meaning in effecting the change that would lead to IAA not just being told to go cry in a corner 9 times out of 10, the NT Rep would need to act in a much more interventionist role.

To address the "isn't always filled anyways" statement, I firmly believe that is because the premise of the IAA is that you make sure the station is following SoP, but they have no power to actually do so, and very few people want to play a job where you cant actually do that job. I think that IA having a strong boss capable (and more importantly willing, such as if he had the same job, but more managerial) of intervention would lead to it being played more, whether that boss is a HoIA or NT Rep is almost irrelevant, but I think lore-wise, the HoIA is the better choice, there is precedent for a Strong IA in NT's Command Structure (See link below), and the NT Rep is already established as an adviser to the ship, not a crewman on it.

As far as a Head of Staff for only one job goes, I think whether that matters is also a matter of opinion/perspective, and when you look at it as IA are basically minders, which is what the wiki page makes them sound like, I don't see why them being segregated into their own pusdo-divison with their own head is a bad thing, less chance for corruption.

I suppose another solution is to just give the IAA the power they need themselves, but that sounds way to abuse-able to me, a head position is much easier to hold accountable, in game and out.

http://80.244.78.90/wiki/index.php/NanoTrasen#Ranking
This HoIA position would be this: " an advisory internal affairs agent is assigned by the Administrative Head of Internal Affairs" when you look at the rankings on the linked page on the wiki, except with a more interventionist role so as to avoid overlapping with the NT rep.

**Comment by IcyV** [comment]
http://80.244.78.90/wiki/index.php/NanoTrasen

Refer to the part that Head of IAA is named as an important CC job that is appointed by very specific people. Through name and power alone I feel this wouldn't really have proper balance or placement on the station.

**Comment by IndexLP** [comment]
Alright so we call it Lead Internal Affairs Agent, there is no name issue then, I used 'Head of' because it's an established title that conveys authority, but that can still be possible with Lead Internal Affairs Agent. As far as the power goes, if CentComm wants to answer their faxes more than 1 time out of 20, and for more than just silly shit, that could work, but that's why this problem exists in the first place, CentComm doesn't and wont, and I don't see why CentComm (The admins) should have to interrupt what they are doing just because the person in charge of the IAA is ignoring them/mia when we should just put into game a way to deal with this issue. I report to my superiors as IAA every time I can, but still have to go to CentComm, as the wiki states you should, in probobly 7-8 out of 10 times because of lack of a superior or one that wont listen.

Here is the thread (http://80.244.78.90/phpBB3/viewtopic.php?f=2&t=1011) I made 3ish months ago on the forums about this very same issue, and it's still real today. At the end Mel mentions using the NT Rep, which if was allowed to directly intervene, would work, but I still think the precedent for the server is an advisory NT rep, not an interventionist one.

**Comment by VampyrBytes** [comment]
The main issue is balance. You're talking about giving the power to demote any head of staff including the captain to a player (non karma at that). This would break at least 2 gamemodes - revolution and mutiny would both become a race to convert this person.

The only way I can see a player having that kind of power working is actually to leave IAA answering to the magistrate and him only being able to approve it after a full jury trial. Anything less is going to end up throwing the balance way off

**Comment by IndexLP** [comment]
He is loyalty implanted, and cannot be converted (Not to mention as a head of Staff he would need to be killed in revolution), assuming the loyalty code was working, so that solves that issue, and during those rounds rule of law/chain of command is already out the window as far as revs/mutineers are concerned, and he is no more of a target than anyone with an ID computer, or access to one.

And on a mutineer round (or any round), IA as a section should already be investigating the captain anyways if he is making strange/asinine requests, that is their job in any (almost) gamemode, with or without this pull request being merged.

A far as demoting a head of staff is concerned anyone with access to an ID computer and that persons ID already can (at least gamewise). As far as RP is concerned, provision that demoting a head of staff (or Captain) requires Central Command Approval OR a consensus among the other heads.

**Comment by VampyrBytes** [comment]
Ok, so I'm now totally confused as to what you want this new position to actually do. Without the authority to demote the heads/captain, I can pretty much guarantee that no-one's going to take any more notice of him than they do of the IAA. They're not going to respect him as a fellow head of staff when he's got a total of 1 person under him and that person's non-essential.

It seems his entire job would consist of sitting around waiting for the IAA to bring a report to him, discuss it with him, and then not be able to do anything more about it than the IAA can already do.

I get that you enjoy IAA and want to make it more relevant, but I don't see this achieving it without giving a player far to much power... power that is for good reason currently in the hands of the admins

off topic slightly, there's at least 2 ways of getting around loyalty implants,,, surgery and kill/clone. As a head rev, I've converted a blueshield before :)

**Comment by IndexLP** [comment]
I disagree with that sentiment whole-heatedly, the demotion of a player does far less to end that round for him than a death does, and that power is in the hands of the players, with very little abuse, relative to how many people play on the server. I fail to see why a demotion of a crewman for IN GAME reasons should reside in the hands of solely the admins, and not the players of said game.

I don't even think you would see any more abuse than in any other position if this job could fire a head. I think it would be a better job with that ability to fire a head for incompetence, but I offered up a compromise because collaboration is about compromising. Would it hurt the jobs authority if it could not fire a head, yes, but being able to fire non-heads still carries a pretty heavy authority with it; I don't think it waters the role down near enough to warrant a "I can pretty much guarantee that no-one's going to take any more notice of him than they do of the IAA." 

As far as 'respect' from other heads go I think that is much more based on the player playing the head. Some players don't respect the other heads when they are head as it is, and some do, because that's the role-play they choose. And besides, even if this position had only a couple people directly under him working for him he has a much wider pool under his oversight.

I think by far you over-estimate the "power" contained in the ability to fire an employee in a game where security forces can use lethal force and Captains can authorize executions as a means to totally end a players game.

**Comment by IndexLP** [comment]
I think it's pretty clear most people on here disagree with the changes so I am going to close my pull request, thanks for considering it, and best of luck with your magistrate changes ponies, I hope they solve the issues I meant this to solve. Again thanks for considering.

**Pull request closed without merging**
