### PR TITLE
Viro Rework

### PR DESCRIPTION
**Pull request by W3bster**
Decided to close and open a whole new PR for formatting.
Screenshots show it all.

http://puu.sh/b2Or6/90ae34d67a.png
http://puu.sh/b2xKu/551c71fde6.png
http://puu.sh/b2xJr/b2fa3acb73.png

### CODE REVIEW

**Comment by W3bster** [comment]
NOTICE : Last screenshot is OUTDATED. To fix the large corridor issue, i expanded cryo a bit. Nothing new, just a bit bigger for more breathing room.

**Comment by M3hillus** [comment]
You should put a food vendor or two in the isolation room area in viro, if people actually end up using it as a quarantine zone.

**Comment by Fox-McCloud** [comment]
Might I suggest implementing Bay's version? It's much more compact and serves, essentially, the same purpose.

**Comment by ZomgPonies** [comment]
Cannot merge.

**Comment by W3bster** [comment]
Remind me why the hell was Bone's uncleaned commit was merged?
Ergh. Now i have to redo my shit.

**Pull request closed without merging**
