### PR TITLE
Added Pancakes + Repaired Potassium and Phosphorus quantities in plants

### PR DESCRIPTION
**Pull request by Tramziller**
I have added too much commits (I wated to add 2 pull request: one for Potas. and Phosp. quantities change and one for pancakes, but I didn't know that I will have to pull all commits at once so I have splitted this into 2 sections to explain all commits.

I have added Pancake and Jam to food recipes. I have added it just
because i need to start coding somewhere and this looked like a nice
opportunity to learn new things. Pancakes are fully tested and works,
with no bugs found. 
Thanks to Spheretech for sprites

I have halfed quantities of ptassium in potatoes and phosphorus in
pumpkins. Now there is about 1-2 units in normal plant...

### CODE REVIEW

**Comment by Tramziller** [comment]
Yes, I have just noticed. I am going to put here corrected version (sorry about that mistake)

**Comment by Tramziller** [comment]
Ok, fixed

**Comment by Tramziller** [comment]
Still no response about this request... if anybody disagrees with changes I made, tell me please

**Comment by ZomgPonies** [comment]
You'll need to update your PR, it's currently unmergeable.

**Comment by Tramziller** [comment]
Ok, I have updated it, I hope it is OK

**Comment by Tramziller** [comment]
by the way, I woulk like to delete the last commit: Merge remote-tracking branch upstream/master from this pull request, because this was just mergign my fork with your fork, so the changes you got there are already made (I hope). Can somebody tell me how can I delete that commit from this pull request?

**Comment by ZomgPonies** [comment]
And of course you STILL managed to fuck it up, I had to fix it upstream after.

**Pull request merged**
