### PR TITLE
Adjusts the grab_neck to be a little less punishing

### PR DESCRIPTION
**Pull request by IcyV**
Changes a constant stun to a short weaken to give a slight chance of getting away.

### CODE REVIEW

**Comment by ghost** [comment]
I disagree with this change.Being grabbed by the neck is very hard to do now anyway, I don't see why we'd need to add the possibility of escape once someone's in the chokehold.

**Comment by IcyV** [comment]
Being choked is still at a later stage. This is just when someone is gripped by the neck. There is other code to resist out of this grip anyway, but that is an impossible feat with the previous infinite stun.

**Comment by ZomgPonies** [comment]
Waiting for more feedback before merging.

**Comment by TheDZD** [comment]
It does not seem to be overly difficult to manage a neck grab on someone with even the disarm stun, as there is a delay between when someone moves out of your grab, and when the grab is actually cancelled. This will result in the victim moving out of an aggressive grab, only for the grabber to quickly upgrade it to a neck grab, pulling the victim onto the grabber's tile, and establishing a neck grab.

In addition to this, when somebody has managed a neck grab on you, there is absolutely no way to escape at that point, due to there being a permanent stun that can transition into oxygen deprivation damage, while ALSO allowing the grabber to attack the victim with whatever is in their other hand. The kill grab also makes any kind of armor worthless in combat if a person can manage a minor stun, due to the fact that it is inescapable and ignores protection from armor. Essentially, a neck grab is a death sentence for anyone that isn't a slime person.

A weaken mitigates the problem of the permanent stun, although something may need to be added to keep the person from yelling for help, as they are being choked.

**Comment by Bone-White** [comment]
I can never get a neck grab on anyone short of a ling para sting.  Flash duration just isn't long enough to get a neck grab, nor is disarm knockdown.  I like being able to RP once you have someone completely pinned to the floor by the neck.  Whispering softly into their ears as you slowly end their life, or give them the terms of their life - handing over their jumpsuit.

I don't see a reason to change this.

**Comment by ZomgPonies** [comment]
Closing due to new changes on grabs.

**Pull request closed without merging**
