### PR TITLE
ESword Changes

### PR DESCRIPTION
**Pull request by ghost**
- All weapons now have a 'no_embed' var. If this var is set to 1 (It is
  0 by default) the item will bypass checks to embed into people during
  melee combat and when thrown. This is intended to be used for items such
  as the esword, where it is physically impossible for it to be embedded
  into someone, as opposed to something like the telebaton, where it's
  simply improbably that would get embedded into anyone.
- All energy-based melee weapons have no_embed set to 1.
- All energy-based melee weapons now have a more appropriate hitsound
  when active. See: blade1.ogg

### CODE REVIEW

**Comment by mvanalphen** [comment]
Err, were these changes mapmerged? I really do not want to spend another two hours (third time) on the camera fixes.

**Comment by ghost** [comment]
They were, I followed instructions provided for the map merge tool.

**Comment by mvanalphen** [comment]
Curious. I made the same changes you did to the armory (https://github.com/Markolie/Paradise/commit/84fd782fa28b9d48e0a75073f5b01dca5fd476cb) to see if it'd resolve the merge conflict, and it only changed the tiles I actually modified.

**Comment by ghost** [comment]
I forgot to delete the backup.dmm, but that's it. That shouldn't be causing the issue, so far as I can tell.

**Comment by mvanalphen** [comment]
Well, it is still very experimental. I've re-done the changes, hopefully they'll get merged quickly.

**Pull request merged**
