### PR TITLE
Magistrate/Psych Office shutter fixes, telescience console UI update, camera fixes, borg movement fix, security windoor fix, CentComm identification computer fix, locker fixes

### PR DESCRIPTION
**Pull request by mvanalphen**
Changes:
1) Removes the magistrate's office door shutters (per http://nanotrasen.se/phpBB3/viewtopic.php?f=12&t=2695).
2) Replaces the magistrate/internal affairs office connector glass airlock with an internal (green) airlock due to the shutters being removed.
3) Fixes the psych's office window shutters (per http://nanotrasen.se/phpBB3/viewtopic.php?f=13&t=2732).
4) Replaces the psych office's glass medbay airlock with a regular medbay airlock, due to the privacy shutters being useless when you can see through the glass door diagonally.
5) Updates the Telescience console to the Nano UI rather than the (old) pop-up system it currently uses. This shouldn't change much aside from a better user experience, as well as the console actually updating when you change the X, Y or Z coordinates (instead of having to re-open the window).
6) Fixes various cameras around the station. First of all, various cameras that were previously inaccessible (Telescience, most of Virology, plenty of Research cameras, various Medbay cameras) are now accessible through the security console (cause of this was them being improperly copied, which resulted in cameras in Virology being called "Supermatter Decontamination"). Secondly, various cameras have been renamed for the sake of consistency (when a part of Virology is prefixed with "Virology", so should the rest of Virology). Thirdly, most camera grouping have been fixed so that the RD doesn't have access to research cameras that security doesn't, and so that the RD also has access to, say, the Toxins Test Area cameras for his viewing pleasure. Also fixes various Mining outpost cameras (per https://github.com/ZomgPonies/Paradise/issues/413, http://nanotrasen.se/phpBB3/viewtopic.php?f=13&t=2173).
7) Fixes the issue where borgs are able to move even though their power cell is taken out or damaged (per http://nanotrasen.se/phpBB3/viewtopic.php?f=13&t=2748).
8) Fixes the left windoor in security, which had the wrong name and color.
9) Fixes the previously broken CentComm Identification Computer, and also fixes some HTML issues both computers had (per https://github.com/ZomgPonies/Paradise/issues/420).
10) Fixes the personal lockers so that they can no longer be locked from inside. Also fixes issue where the personal lockers kept saying "It won't budge" even though it opened (per https://github.com/ZomgPonies/Paradise/issues/452).
11) Fixes lockers so that they can no longer be welded open or shut from the inside (per http://nanotrasen.se/phpBB3/viewtopic.php?f=13&t=2773).
12) Fixes an issue where lockers couldn't be closed when in front of a fire-axe cabinet (per http://nanotrasen.se/phpBB3/viewtopic.php?f=13&t=2773)

Note: Changes to the back-up files can be disregarded.

### CODE REVIEW

**Comment by mvanalphen** [comment]
Apologies for having to collect these commits in a single pull request - unfortunately enough Github doesn't allow me to create separate pull requests for different commits without creating a new fork, which I think is a bit excessive.

I might be doing some more UI updating for various consoles in the near future to ensure they all use the Nano UI and update properly.

**Comment by mvanalphen** [comment]
Fixed the merge conflict.

**Comment by Fox-McCloud** [comment]
Main concern about this patch: Robot movement when cell is removed. I'm not sure if this is a bug or not; could you confirm what the behavior for this is on Bay and TG?

I'll also point out that you may have to re-do the Telescience menu fixes, at a later date; porting TG telesci is likely to happen after the Nuke Ops rework is finished (Para is currently running a horrendously outdated alpha version of telesci).

**Comment by mvanalphen** [comment]
I'm not sure about /tg/, but I do know Baystation prevents borgs from moving when they don't have any power due to the cell being taken out (https://github.com/Baystation12/Baystation12/blob/master/code/modules/mob/living/silicon/robot/robot_movement.dm#L26). I was going to copy over their method of doing it, but they reworked the entire borg power system, which meant we'd have to do a major patch for borgs to fix this minor issue. Hence why I couldn't just do a check for cell_use_power returning 1, but had to work around it. 

And I don't mind redoing the telescience console at all (assuming /tg/ hasn't done it themselves).

**Comment by Fox-McCloud** [comment]
Oki doke. OKi doke, thanks. I'll go ahead and merge this in then. Thanks!

**Pull request merged**
