### PR TITLE
Fix restricted and protected jobs

### PR DESCRIPTION
**Pull request by Robertha89**
Added several jobs to restricted and protected jobs.

### CODE REVIEW

**Comment by alex-gh** [comment]
I understand the changes to the protected jobs list, but why the changes to the restricted job list?

**Comment by Robertha89** [comment]
protected job is what can't be the antag type at all, cause traitor captain and traitor ling seems od, along the line of the chaplain cant be a cultist.
Restricted is based upon the list from normal traitormode, and contains all security jobs and loyalty implanted people, they can't join as traitor, changeling or cultist, but can still be culted or reved if the loyalty implant is removed except for the protected jobs.

**Comment by alex-gh** [comment]
Adding "Nanotrasen Recruiter" to protected jobs is welcome, since we don't want them to spawn as antags (Except in cases like autotraitor and traitorchan since they inherit from the base class). 

But I don't see how changes to the restricted jobs would help us: They are not checked when converting on rev and cult. And since we use "protect_roles_from_antagonist" they are synonymous with protected jobs anyways.

**Comment by Robertha89** [comment]
Oh, in that case, so undo the changes to the cult, add nt rec to restricted job there then? This would make it fine yes?

**Comment by alex-gh** [comment]
Well, just add "Nanotrasen Recruiter" to the protected or restricted job list wherever apropriate.
Do not make changes to autotraitor.dm and traitor_chan.dm since they inherit from traitor and autotraitor.

**Comment by Robertha89** [comment]
There we go, should be fixed.

**Comment by alex-gh** [comment]
Yep, looks good. Thank you!

**Comment by ZomgPonies** [comment]
Can't automerge, needs update.

**Pull request closed without merging**
